CREATE TABLE troubleshooter_pages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lang VARCHAR(8) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    title TEXT,
    content MEDIUMTEXT,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY lang_slug (lang, slug)
);

CREATE TABLE support_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page VARCHAR(64) NOT NULL,
    language VARCHAR(8) NOT NULL,
    f1 TEXT, f2 TEXT, f3 TEXT, f4 TEXT, f5 TEXT,
    f6 TEXT, f7 TEXT, f8 TEXT, f9 TEXT, f10 TEXT,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);
