ALTER TABLE custom_pages
    DROP PRIMARY KEY,
    ADD COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    MODIFY theme VARCHAR(255) DEFAULT NULL,
    ADD UNIQUE KEY slug_theme (slug, theme);
