CREATE TABLE IF NOT EXISTS map_contest_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    full_name VARCHAR(255) NOT NULL,
    address VARCHAR(255) DEFAULT NULL,
    city VARCHAR(100) DEFAULT NULL,
    state VARCHAR(100) DEFAULT NULL,
    country VARCHAR(100) DEFAULT NULL,
    zip VARCHAR(20) DEFAULT NULL,
    dob VARCHAR(20) DEFAULT NULL,
    phone VARCHAR(50) DEFAULT NULL,
    email VARCHAR(255) NOT NULL,
    group_name VARCHAR(255) DEFAULT NULL,
    group_member1 VARCHAR(255) DEFAULT NULL,
    group_member2 VARCHAR(255) DEFAULT NULL,
    group_member3 VARCHAR(255) DEFAULT NULL,
    group_member4 VARCHAR(255) DEFAULT NULL,
    map_name VARCHAR(255) DEFAULT NULL,
    map_file VARCHAR(255) DEFAULT NULL,
    source_files VARCHAR(255) DEFAULT NULL,
    map_description TEXT,
    recommended_players VARCHAR(50) DEFAULT NULL,
    game_mode VARCHAR(50) DEFAULT NULL,
    development_time VARCHAR(50) DEFAULT NULL,
    tools VARCHAR(255) DEFAULT NULL,
    inspiration TEXT,
    screenshot1 VARCHAR(255) DEFAULT NULL,
    screenshot2 VARCHAR(255) DEFAULT NULL,
    screenshot3 VARCHAR(255) DEFAULT NULL,
    previous_experience TEXT,
    additional_comments TEXT,
    how_did_you_hear VARCHAR(255) DEFAULT NULL,
    original_work TINYINT(1) DEFAULT 0,
    agree_rules TINYINT(1) DEFAULT 0,
    agree_license TINYINT(1) DEFAULT 0,
    confirm_age TINYINT(1) DEFAULT 0,
    UNIQUE KEY uniq_name_email (full_name,email)
);
