CREATE TABLE IF NOT EXISTS tournaments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    game VARCHAR(255) DEFAULT NULL,
    host VARCHAR(255) DEFAULT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP
);
