services:
    steamcms.historical_filter.listener:
        class: steamcms\historical_filter\event\main_listener
        arguments:
            - '@user'
            - '@template'
        tags:
            - { name: event.listener }
