<table align="center" border="0" cellpadding="0" cellspacing="0" cool="" gridx="16" gridy="16" height="77" showgridx="" showgridy="" width="803">
<tbody><tr height="2">
<td colspan="4" height="2" width="802"></td>
<td height="2" width="1"><spacer height="2" type="block" width="1"></spacer></td>
</tr>
<tr height="34">
<td colspan="2" height="34" width="356"></td>
<td align="left" height="34" valign="top" width="420" xpos="356"><img border="0" height="23" src="../images/2002_forum/support/LOGO_Valve.01.gif" width="82"></td>
<td height="74" rowspan="2" width="26"></td>
<td height="34" width="1"><spacer height="34" type="block" width="1"></spacer></td>
</tr>
<tr height="40">
<td height="40" width="24"></td>
<td align="left" colspan="2" content="" csheight="40" height="40" valign="top" width="752" xpos="24">
<div align="center">
<p><b><font face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular" size="2"><a href="../index.php">Home</a></font></b> |<b> </b><b><a href="../support.php">Support</a></b> |<b> </b><b><a href="index.php">Forums</a></b><b> | </b><b><a href="../faq.php">Bugs</a></b><b> | </b><b><a href="../support.php#troubleshooting">Troubleshooting</a></b><b> | </b><b><a href="../support.php#contact">Contact</a></b><br>
<font face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular" size="1">&copy; 2002 Valve, L.L.C. All rights reserved. Steam, the Steam logo, Valve, and the Valve logo are trademarks and/or registered trademarks of Valve, L.L.C.</font></p>
</div>
</td>
<td height="40" width="1"><spacer height="40" type="block" width="1"></spacer></td>
</tr>
<tr cntrlrow="" height="1">
<td height="1" width="24"><spacer height="1" type="block" width="24"></spacer></td>
<td height="1" width="332"><spacer height="1" type="block" width="332"></spacer></td>
<td height="1" width="420"><spacer height="1" type="block" width="420"></spacer></td>
<td height="1" width="26"><spacer height="1" type="block" width="26"></spacer></td>
<td height="1" width="1"></td>
</tr>
</tbody></table>