<!DOCTYPE html>
<html>
<head>
  <title>Steam Support Site</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<!-- global colours copied from the 2002 page -->
<body bgcolor="#626D5C"
      text="#C4CABE"
      link="#BFBA50"
      vlink="#938F3C"
      alink="#938F3C">

<!-- set the default face / size / colour once -->
<basefont face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular" size="2" color="#C4CABE">


<table align="center" bgcolor="#000000" border="0" cellpadding="0" cellspacing="0" cool="" gridx="16" gridy="16" height="135" showgridx="" showgridy="" width="800">
<tbody><tr height="16">
<td colspan="5" height="16" width="799"><spacer height="16" type="block" width="799"></spacer></td>
<td height="16" width="1"><spacer height="16" type="block" width="1"></spacer></td>
</tr>
<tr height="38">
<td colspan="2" height="38" width="17"><spacer height="38" type="block" width="17"></spacer></td>
<td align="left" colspan="3" height="38" valign="top" width="782" xpos="17"><img border="0" height="29" src="support/Images/Type_SupportSite2.jpg" width="770"></td>
<td height="38" width="1"><spacer height="38" type="block" width="1"></spacer></td>
</tr>
<tr height="18">
<td colspan="3" height="18" width="241"><spacer height="18" type="block" width="241"></spacer></td>
<td align="left" content="" csheight="71" height="80" rowspan="2" valign="top" width="545" xpos="241">
<div align="right">
<font face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular" size="2"><b><a href="../index.php">Home</a></b> |<b> </b><b><a href="../support.php">Support</a></b> |<b> </b><b><a href="index.php">Forums</a></b><b> | </b><b><a href="../faq.php">Bugs</a></b><b> | </b><b><a href="../support.php#troubleshooting">Troubleshooting</a></b><b> | </b><b><a href="../support.php#contact">Contact</a></b></font><br>
<font face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular" size="1"><a href="signup.php">Create Account</a> | <a href="account.php">Account Options</a> | <a href="password_reset.php">Lost Password</a> | <a href="messages.php">Private Messages (?)</a></font>
</div>
</td>
<td height="80" rowspan="2" width="13"><spacer height="80" type="block" width="13"></spacer></td>
<td height="18" width="1"><spacer height="18" type="block" width="1"></spacer></td>
</tr>
<tr height="62">
<td height="62" width="15"><spacer height="62" type="block" width="15"></spacer></td>
<td align="left" colspan="2" height="62" valign="top" width="226" xpos="15"><img border="0" height="51" src="support/Images/Logo_Steam2.jpg" width="188"></td>
<td height="62" width="1"><spacer height="62" type="block" width="1"></spacer></td>
</tr>
<tr cntrlrow="" height="1">
<td height="1" width="15"><spacer height="1" type="block" width="15"></spacer></td>
<td height="1" width="2"><spacer height="1" type="block" width="2"></spacer></td>
<td height="1" width="224"><spacer height="1" type="block" width="224"></spacer></td>
<td height="1" width="545"><spacer height="1" type="block" width="545"></spacer></td>
<td height="1" width="13"><spacer height="1" type="block" width="13"></spacer></td>
<td height="1" width="1"><spacer height="1" type="block" width="1"></spacer></td>
</tr>
</tbody></table>