-- Prefilled from archived 2004/2005 third-party games
INSERT INTO `0405_storefront_thirdpartGames` (title,description,image_thumb,image_screenshot,websiteUrl,isHidden) VALUES
('NATURAL SELECTION V3.0 (BETA)','Natural Selection blends first-person combat with real-time strategy. It features intense ''marines vs. aliens'' teamplay, where one marine can become ''Commander''. The Commander plays from a top-down strategic perspective and leads live players. The aliens can evolve upgrades like Cloaking and Scent of Fear, and can change lifeforms to run on walls, fly and even devour marines whole. NS has atmospheric indoor sci-fi environments full of steam and smoke, and features orchestral music from Jeremy Soule.','/storefront/images/t1_1.gif','/storefront/images/t2_1.gif','http://www.natural-selection.org/',0),
('THE SPECIALISTS','The Specialists mod turns Valve''s seminal FPS into an action packed, trick-filled deathmatch.','/storefront/images/t1_2.gif','/storefront/images/t2_2.gif','http://www.specialistsmod.net/',0),
('SVEN CO-OP','Sven Co-op offers the unique gameplay of single player Half-Life... but you can bring your friends with you. Together you can play the original missions, or choose from over 200 custom maps & missions created specifically for Sven.','/storefront/images/t1_4.gif','/storefront/images/t2_4.gif','http://www.svencoop.com/',0),
('DIGITAL PAINTBALL','Digital Paintball seeks to bring the fast and furious gameplay of paintball to the home pc. The gameplay is somewhat unique: You start out with a fixed amount of ''credits'', with which you can purchase any equipment that you want. Game modes include capture the flag, elimination, center flag, or attack+defend.','/storefront/images/t1_5.gif','/storefront/images/t2_5.gif','http://www.digitalpaintball.net/',0),
('THE BATTLE GROUNDS','The Battle Grounds places you in the time period of the revolutionary war in America. American rebels are fighting for their freedom and the troops of the british crown are trying to keep control of the colonies.','/storefront/images/t1_8.gif','/storefront/images/t2_8.gif','http://www.bgmod.com/',0),
('EARTH''S SPECIAL FORCES','ESF is based on an animated television series... Do your favorite character''s signature moves while running, jumping, flying and teleporting around huge maps. Use abilities such as melee, transform, power struggling, attack swatting and more...','/storefront/images/t1_7.gif','/storefront/images/t2_7.gif','http://www.esforces.com/',0),
('FIREARMS','Firearms focuses on teamplay with Half-Life gameplay altered to the extreme. New rules, new content, and 30 new weapons. It features multiplay only, and therefore it is only playable online or on a local area network.','/storefront/images/t1_6.gif','/storefront/images/t2_6.gif','http://firearmsmod.com/',0),
('HOSTILE INTENT','Hostile Intent for all intents and purposes is the thinking man''s First Person Shooter. In Hostile Intent the player has to use cover wisely, conserve his ammo, work well with his teammates, use communication effectively, keep the mission at the forefront of his mind and especially keep his cool under fire.','/storefront/images/t1_10.gif','/storefront/images/t2_10.gif','http://www.hostileintent.org/',0),
('VAMPIRE SLAYER','Vampire Slayer is a teamplay mod where two sides battle it out in a variety of atmospheric settings. Good versus evil, guns versus agility, Slayers versus Vampires! Do you want guns and stakes? Or would you like to drink blood and leap off buildings at your prey? Includes bots for offline play.','/storefront/images/t1_12.gif','/storefront/images/t2_12.gif','http://www.planethalflife.com/vampire',0),
('HALF-LIFE RALLY V1.0 (BETA)','Half-Life Rally is a car racing game. The goal is simply to race cars and be the first and fastest across the finish line, out-running your opponents in any way possible to gain a few milliseconds on them.','/storefront/images/t1_14.gif','/storefront/images/t2_14.gif','http://www.hlrally.net/',0),
('INTERNATIONAL ONLINE SOCCER','IOS is a first and third person online multiplayer soccer game that aims to be the online equivalent of great console soccer games but with a true multiplayer teamplay experience.','/storefront/images/t1_11.gif','/storefront/images/t2_11.gif','http://www.planethalflife.com/ios/',0),
('THE SHIP','Welcome to The Ship, and congratulations! You''ve just won a free ticket to a dream cruise onboard a spectacular, replica 1920''s cruise ship! You might find a few things to concern you while you''re enjoying the luxurious surroundings, like the fact that you have the name of another passenger...','/storefront/images/t1_18.gif','/storefront/images/t2_18.gif','http://www.theshiponline.com/',0),
('SCIENCE AND INDUSTRY','Science and Industry is a teamplay mod for Half-Life, in which players assume the role of Security Officer in one of two rival corporations striving for domination in the cutthroat world of chemical and weapons research and development.','/storefront/images/t1_16.gif','/storefront/images/t2_16.gif','http://www.planethalflife.com/si/',0),
('FRONTLINE FORCE','Frontline Force','/storefront/images/t1_15.gif','/storefront/images/t2_15.gif','http://www.frontlineforce.com/',0),
('ADRENALINE GAMER','More control... More action... More adrenaline','/storefront/images/t1_9.gif','/storefront/images/t2_9.gif','http://www.planethalflife.com/agmod/',0),
('ACTION HALF-LIFE','Action Half Life is designed to simulate the experience of being in an Action movie, and aims for something called ''Movie Realism.'' This means that you can take a few bullets and keep fighting. You can fall from a two story roof and only hurt your leg. You can bandage a wound in seconds.','/storefront/images/t1_13.gif','/storefront/images/t2_13.gif','http://ahl.telefragged.com/',0),
('HALF-LIFE ELITE','Half-Life Elite is a modification of standard Half-Life Deathmatch with new added features which raise the precision, diversity and competition of the game! The mod features eight modes of play, seven of which are new! Added features like radar, waypoint teammate tracking, and team status have improved the deathmatch teamplay.','/storefront/images/t1_17.gif','/storefront/images/t2_17.gif','http://www.hl-elite.com/',0);
