CREATE TABLE sidebar_sections (
    section_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    icon_path VARCHAR(255) DEFAULT NULL,
    is_collapsible TINYINT(1) NOT NULL DEFAULT 0,
    collapsible_id VARCHAR(255) DEFAULT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sidebar_section_variants (
    variant_id INT AUTO_INCREMENT PRIMARY KEY,
    section_id INT NOT NULL,
    theme_list VARCHAR(255) NOT NULL,
    html_content TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (section_id) REFERENCES sidebar_sections(section_id) ON DELETE CASCADE
);
