-- Prefilled from archived 2004/2005 storefront games
INSERT INTO `0405_storefront_games` (appid,title,description,image_thumb,image_screenshot,purchaseButtonStr,isHidden) VALUES
(220,'HALF-LIFE 2','Half-Life 2 defines a new benchmark in gaming with startling realism and responsiveness. Powered by Source&trade; technology, Half-Life 2 features the most sophisticated in-game characters ever witnessed, advanced AI, stunning graphics and physical gameplay.','/storefront/images/gi1_220.gif','/storefront/images/gi2_220.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(240,'COUNTER-STRIKE: SOURCE','THE NEXT INSTALLMENT OF THE WORLD''S # 1 ONLINE ACTION GAME Counter-Strike: Source blends Counter-Strike''s award-winning teamplay action with the advanced technology of Source&trade; technology. Featuring state of the art graphics, all new sounds, and introducing physics, Counter-Strike: Source is a must-have for every action gamer.','/storefront/images/gi1_240.gif','/storefront/images/gi2_240.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(280,'HALF-LIFE: SOURCE','Winner of over 50 Game of the Year awards, Half-Life set new standards for action games when it was released in 1998. Half-Life: Source is a digitally remastered version of the critically acclaimed and best selling PC game, enhanced via Source&trade; technology to include physics simulation, enhanced effects, and more.','/storefront/images/gi1_280.gif','/storefront/images/gi2_280.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(70,'HALF-LIFE','Named Game of the Year by over 50 publications, Valve&apos;s debut title blends action and adventure with award-winning technology to create a frighteningly realistic world where players must think to survive. Also includes an exciting multiplayer mode that allows you to play against friends and enemies around the world.','/storefront/images/gi1_5.gif','/storefront/images/gi2_5.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(10,'COUNTER-STRIKE','Play the world&apos;s number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team&apos;s success. Your team''s success affects your role.','/storefront/images/gi1_7.gif','/storefront/images/gi2_7.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(80,'COUNTER-STRIKE: CONDITION ZERO','With its extensive Tour of Duty campaign, a near-limitless number of skirmish modes, updates and new content for Counter-Strike''s award-winning multiplayer game play, plus over 12 bonus single player missions, Counter-Strike: Condition Zero is a tremendous offering of single and multiplayer content.','/storefront/images/gi1_8.gif','/storefront/images/gi2_8.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(100,'CONDITION ZERO DELETED SCENES','A series of stand-alone, single-player missions for Counter-Strike, Condition Zero Deleted Scenes assigns players to over one dozen standoffs around the globe. Features exclusive items and weapons.','/storefront/images/gi1_10.gif','/storefront/images/gi2_10.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(30,'DAY OF DEFEAT','Enlist in an intense brand of Axis vs. Allied teamplay set in the WWII European Theatre of Operations. Players assume the role of light/assault/heavy infantry, sniper or machine-gunner class, each with a unique arsenal of historical weaponry at their disposal. Missions are based on key historical operations. And, as war rages, players must work together with their squad to accomplish a variety of mission-specific objectives.','/storefront/images/gi1_9.gif','/storefront/images/gi2_9.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(20,'TEAM FORTRESS CLASSIC','One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities, as teams compete online in a variety of game play modes.','/storefront/images/gi1_11.gif','/storefront/images/gi2_11.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(40,'DEATHMATCH CLASSIC','Enjoy fast-paced multiplayer gaming with Deathmatch Classic (a.k.a. DMC). Valve''s tribute to the work of id software, DMC invites players to grab their rocket launchers and put their reflexes to the test in a collection of futuristic settings.','/storefront/images/gi1_12.gif','/storefront/images/gi2_12.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(50,'OPPOSING FORCE','Return to the Black Mesa Research Facility as one of the military specialists assigned to eliminate Gordon Freeman. Experience an entirely new episode of single player action. Meet fierce alien opponents, and experiment with new weaponry. Named ''Game of the Year'' by the Academy of Interactive Arts and Sciences.','/storefront/images/gi1_13.gif','/storefront/images/gi2_13.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(60,'RICOCHET','A futuristic action game that challenges your agility as well as your aim, Ricochet features one-on-one and team matches played in a variety of futuristic battle arenas.','/storefront/images/gi1_14.gif','/storefront/images/gi2_14.gif','CLICK for PURCHASE OPTIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',0),
(92,'CODENAME GORDON','Created by Nuclearvision Entertainment, Codename Gordon takes players through dozens of levels inspired by Half-Life and Half-Life 2, challenges players to a slew of puzzles, and showcases many of the familiar creatures in an all new, 2 dimensional playing field.','/storefront/images/gi1_17.gif','/storefront/images/gi2_11.gif','',0);
