-- Steam Platform Update History
-- App ID: 300
-- Generated on: 2025-08-01 23:34:56
-- MySQL/MariaDB Format



INSERT INTO `platform_update_history` (`appid`, `date`, `title`, `content`) VALUES
(300, '2004-10-05', NULL, '<div class=\"details\" id=\"October 5, 2004\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added Day of Defeat: Source to <em>Coming Soon</em>.</li> </ul>
</div>'),
(300, '2005-09-26', 'Day Of Defeat: Source Available Now', '<div class=\"post_content\" id=\"content_449\" style=\"display: none;\">
<p>Day of Defeat: Source is available now via Steam for just $19.95. If you have Steam installed, you can <a href=\"steam://run/300\">get Day of Defeat now</a>! If you don\'t have Steam installed yet, <a href=\"http://steampowered.com/?area=getsteamnow\">click here for the Steam installer<a>.</a></a></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-09-27', NULL, '<div class=\"details\" id=\"September 27, 2005\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added the default mapcycle.txt to servers running Day of Defeat: Source</li> <li> Changed refresh behavior of server browser. Old behavior was generating too much traffic when list was not open</li> </ul>
Bug fixes
	<ul>
<li> Fixed crash bug when using %s in your player name</li> <li> Fixed some video cards being incorrectly set to DX9 when they should have been DX8. This would cause a significant performance problem for affected hardware</li> <li> Fixed bug where VAC would sometimes hold onto .dlls after a game had been shut down completely</li> <li> Fixed a crash which could sometimes occur immediately after launching a game</li> </ul>
</div>'),
(300, '2005-09-27', 'Day Of Defeat: Source And Source Engine Updates Available', '<div class=\"post_content\" id=\"content_450\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source and the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed some video cards being incorrectly set to DX9 when they should have been DX8. This would cause a significant performance problem for affected hardware<br/><li>Changed refresh behavior of server browser. Old behavior was generating too much traffic when list was not open<br/><li>Fixed bug where VAC would sometimes hold onto .dlls after a game had been shut down completely<br/><li>Fixed a crash which could sometimes occur immediately after launching a game<br/></li></li></li></li></ul><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added the default mapcycle.txt to servers running Day of Defeat: Source<br/><li>Fixed crash bug when using %s in your player name<br/></li></li></ul><br/><b>Source Dedicated Server</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed bug in dedicated server engine that incorrectly displayed their anti-cheat status (servers were showing as insecure, but were running in secure mode)</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-10-03', 'Source Engine And Half-life 1: Engine Updates Available', '<div class=\"post_content\" id=\"content_452\" style=\"display: none;\">
<p>Updates to the Source Engine and Half-Life 1: Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed loading error when trying to debug Source MODs using the SDK<br/><li>Fixed a startup crash in Windows 98<br/></li></li></ul><br/><b>Half-Life 1: Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed name exploit causing client crash</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-10-19', NULL, '<div class=\"details\" id=\"October 19, 2005\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added defense scoring bonus. Players now get a point for blocking an area cap that is over 50%, either by killing a player required for the capture, or by entering the capture area</li> <li> Changed to new arm hitbox code - uses hitbox groups to swap between hitbox sets with and without arms. This will prevent shots to the chest area from hitting the target player\'s arms</li> <li> Increased Thompson and MP40 melee attack rate to match knife/spade</li> <li> Fixed situation where melee attacks weren\'t hitting target when they should have</li> <li> Darkened background of scoreboard to make it easier to read</li> <li> K98 iron sights no longer re-zooms after a shot</li> <li> Fixed rag doll pose when player went prone with Panzerschreck</li> <li> Reduced maximum number of players on a server to 32</li> <li> Fixed issue with bullet penetration wasn\'t happening correctly with displacements</li> <li> Optimization related to grenade explosions</li> <li> Network optimizations for player, player resource</li> <li> Restrict which shaders are allowed to be applied to player models</li> <li> Friendly fire is now turned off for the bonus round. Be nice to your winning teammates</li> <li> Crosshair scale setting is now saved across sessions</li> <li> Added log event for tick points</li> <li> Added log event for changeclass</li> <li> Added log event for flag caps</li> <li> Added log event for game over condition</li> <li> Added damage, hitbox, weapon info to player_hurt event</li> <li> Fixed log events for clan restart events</li> <li> Added cvar mp_logdetail ( 0 = no damage logged, 1 = enemy damage, 2 = teammate damage, 3 = both )</li> <li> Made input to voice menus all client side</li> </ul>
Bug fixes
	<ul>
<li> Fixed an issue with players not respawning on round restart</li> <li> Fixed accuracy on semi-auto and full-auto for bar and MP44 being swapped. Semi automatic is now more accurate than fully automatic</li> <li> Fixed sniper rifle playing zoom out animation out if the player was not on the ground when they tried to zoom in ( e.g., falling off of a small ledge )</li> </ul>
</div>'),
(300, '2005-10-19', 'Day Of Defeat: Source And Source Engine Updates Available', '<div class=\"post_content\" id=\"content_466\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source and the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>cl_predict is now treated as a cheat<br/><li>Disallow the \'%\' character in names and the \'#\' character when at the start of a name<br/><li>Removed debug cvar snd_mixvol</li></li></li></ul><br/><br/><b>Day of Defeat Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added defense scoring bonus. Players now get a point for blocking an area cap that is over 50%, either by killing a player required for the capture, or by entering the capture area<br/><li>Fixed an issue with players not respawning on round restart<br/><li>Changed to new arm hitbox code - uses hitbox groups to swap between hitbox sets with and without arms. This will prevent shots to the chest area from hitting the target player\'s arms<br/><li>Increased Thompson and MP40 melee attack rate to match knife/spade<br/><li>Fixed situation where melee attacks weren\'t hitting target when they should have<br/><li>Fixed accuracy on semi-auto and full-auto for bar and MP44 being swapped<br/><li>Semi automatic is now more accurate than fully automatic<br/><li>Darkened background of scoreboard to make it easier to read<br/><li>K98 iron sights no longer re-zooms after a shot<br/><li>Fixed rag doll pose when player went prone with Panzerschreck<br/><li>Reduced maximum number of players on a server to 32<br/><li>Fixed issue with bullet penetration wasn\'t happening correctly with displacements<br/><li>Optimization related to grenade explosions<br/><li>Network optimizations for player, player resource<br/><li>Restrict which shaders are allowed to be applied to player models.<br/><li>Fixed sniper rifle playing zoom out animation out if the player was not on the ground when they tried to zoom in ( e.g., falling off of a small ledge )<br/><li>Friendly fire is now turned off for the bonus round. Be nice to your winning teammates<br/><li>Crosshair scale setting is now saved across sessions<br/><li>Added log event for tick points<br/><li>Added log event for changeclass<br/><li>Added log event for flag caps<br/><li>Added log event for game over condition<br/><li>Added damage, hitbox, weapon info to player_hurt event<br/><li>Fixed log events for clan restart events<br/><li>Added cvar mp_logdetail ( 0 = no damage logged, 1 = enemy damage, 2 = teammate damage, 3 = both )<br/><li>Made input to voice menus all client side<br/></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-11-22', 'Day Of Defeat: Source Update Available', '<div class=\"post_content\" id=\"content_482\" style=\"display: none;\">
<p>An update to Day of Defeat: Source has been released. The update will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Updated gameinfo.txt to support the Source SDK</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-11-30', NULL, '<div class=\"details\" id=\"November 30, 2005\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added new map dod_argentan</li> </ul>
</div>'),
(300, '2005-11-30', 'Day Of Defeat: Source And Rag Doll Kung Fu Update Available', '<div class=\"post_content\" id=\"content_486\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source and Rag Doll Kung Fu have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added new map <i>dod_argentan</i><br/></li></ul><br/><b>Rag Doll Kung Fu</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed not being able to play past the second level transition<br/></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2005-12-20', 'Counter-strike: Source Update Available', '<div class=\"post_content\" id=\"content_495\" style=\"display: none;\">
<p>Updates to Counter-Strike: Source have been released. The updates will be applied automatically when your Steam client is restarted.</p>
<br clear=\"left\"/>
</div>'),
(300, '2005-12-22', NULL, '<div class=\"details\" id=\"December 22, 2005\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Allied Garand is now more accurate</li> <li> Allied 30cal machine gun is now more accurate</li> <li> Made the garand sight ring larger when in iron sights.</li> <li> Moved Axis k98 rifle iron sight model away from the player slightly.</li> <li> View model no longer sways in iron sight mode</li> <li> Decreased the recoil on the Allied Garand when in iron sights.</li> <li> Fixed bug where Allied 30cal machine gun would remove stamina when firing an empty gun</li> <li> Improved weapon pickup to search in radius around crosshair</li> <li> Fixed prediction bug where players would get stuck together</li> <li> Added an end of round statistics panel to highlight the most valuable contributors to the winning team.</li> <li> Increased footstep volume</li> <li> Updated firing sounds for both Allied and Axis machine guns.</li> <li> Game now uploads a stats blob to steam on level change or shutdown. Contains info about scoring, weapon and class performance and server settings. We\'ll be creating a web page for the community to view these stats soon. (These are not statistics about individual players, just aggregate across the entire Day of Defeat Source community.)</li> <li> Added life id to damage record in console</li> <li> Fixed bug that would produce \'0 damage in x hits\' in damage record</li> <li> Added cvar \"hud_takesshots\" - Setting this to 1 will take a screen shot at the end of the game with the scoreboard included.</li> <li> Updated the death notice hud element</li> <li> Fixed logging error where player index was used instead of userid for cap and block messages</li> <li> Winning and losing teams can now chat during the bonus round * no longer show (dead) prefix during this period.</li> <li> Fixed bug where last character of a players name would be cut off.</li> <li> Added defense icon to death notice defense event instead of \"Defended\" text</li> <li> Fixed bug where you could jump while in the process of going prone</li> <li> Fixed animation bug when an assault player dropped his primary weapon and didn\'t have a pistol or grenades.</li> <li> Force exact file consistency on smoke grenade materials and weapon scripts</li> <li> Optimizations to lag compensation</li> <li> Added voice command variations</li> <li> Optimizations to debris physboxes</li> </ul>
</div>'),
(300, '2005-12-22', 'Day Of Defeat: Source Update Available', '<div class=\"post_content\" id=\"content_497\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source have been released. The updates will be applied automatically when your Steam client is restarted.</p>
<br clear=\"left\"/>
</div>'),
(300, '2006-01-09', 'Source Engine Update Available', '<div class=\"post_content\" id=\"content_498\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed problem users with ATI cards were experiencing with overly shiny cube maps</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-01-17', 'Source Engine Sdk Update Released', '<div class=\"post_content\" id=\"content_500\" style=\"display: none;\">
<p>A major update to the Source SDK has been released on Steam. Included in this update are several features and fixes for the tools in the Source SDK. <br/><br/><b>New SDK Features</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>High Dynamic Range lighting now supported in the tools<br/><li>Day of Defeat: Source support now included<br/><li>New Hammer Editor features:<br/> <ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>VGUI Model browser with real-time 3D view<br/> <li>Map autosave/backup<br/> <li>Model and displacement rendering in 2D views<br/> <li>Many other small improvements and bug fixes <br/></li></li></li></li></ul></li></li></li></ul><br/>For a full list of changes, see the <a href=\"http://developer.valvesoftware.com/wiki/Source_SDK_Release_Notes\">Source SDK Changelist</a> on the <a href=\"http://developer.valvesoftware.com/\">Valve Developer Community site</a></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-01-25', NULL, '<div class=\"details\" id=\"January 25, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added dod_kalt with High Dynamic Range (HDR) lighting</li> </ul>
Bug fixes
	<ul>
<li> Fixed players getting stuck on models</li> </ul>
</div>'),
(300, '2006-01-25', 'Day Of Defeat: Source Update Available', '<div class=\"post_content\" id=\"content_504\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>New Map</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added dod_kalt with High Dynamic Range (HDR) lighting<br/></li></ul><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed players getting stuck on models<br/></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-04-19', NULL, '<div class=\"details\" id=\"April 19, 2006\" style=\"display: none;\">
Bug fixes
	<ul>
<li> Fixed long really long game directories not being able to upload game statistics</li> <li> Fixed listen server host not being able to hear sounds from bsp .zip files</li> <li> Fixed demo smoother not being able to select samples in certain demo files</li> <li> Fixed partial-HDR exploit in DX7 allowing wireframe materials</li> </ul>
</div>'),
(300, '2006-05-24', 'Source Engine Update Available', '<div class=\"post_content\" id=\"content_630\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Graphics</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed occasional graphics artifact tearing run running on Nvidia 6800 hardware<br/><li>Fixed mismatch of bumpmapped/non-bumpmapped surfaces in HDR<br/><li>Fixed bug where <i>mat_colorcorrection</i> wasn\'t getting set properly on when running for the first time<br/><li>Updated default configuration settings for some newer video cards<br/><li>Fixed full-screen flicker bug when Alt-Tabbing out of fullscreen (particularly at high resolutions)<br/></li></li></li></li></li></ul><br/><b>User Interface</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added progress bar state to print a description when the server changes levels<br/><li>Show disconnect dialog when client connection times out<br/><li>Fixed anti-aliasing on fonts<br/><li>Fixed a memory leak in vgui<br/><li>Fix for startup video not showing correctly if running fullscreen with desktop resolution less than or equal to 1024x768<br/><li>Fixed bug where game would crash when taking a bug screenshot if the screen/window resolution was wider that 2048 pixels<br/></li></li></li></li></li></li></ul><br/><b>Sound</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed sound initializing twice at startup in some cases<br/><li>Optimized sound engine performance<br/><li>Fixed a bug where machines without proper sound hardware and/or drivers would crash<br/></li></li></li></ul><br/><b>SourceTV</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added SourceTV port and delay time to <i>status</i> output if SourceTV is active<br/><li>Added new command <i>net_status</i> that shows more detailed information about total and average packet loss, latency, packets/sec and bandwidth<br/><li>Added convar <i>tv_autoretry 1</i> so relay proxies try to reconnect after connection crashed/timed out<br/><li>Added convar <i>tv_timeout</i> to specify connection timeout limit in seconds<br/><li>Improved spectator client dispatching, should be faster and balance better<br/><li>Fixed SourceTV relays being unable to connect to <i>sv_lan 1</i> servers<br/><li>Fixed SourceTV servers reporting password restrictions<br/><li>Fixed SourceTV bots joining game even if disabled <br/><li>Fixed disappearing weapons in SourceTV<br/><li>Fixed spectator chat not displaying on relay proxies<br/><li>Fixed SourceTV crash during changelevel<br/><li>Fixed command <i>tv_record</i> crashing relay proxies<br/><li>Reduced SourceTV CPU requirements<br/></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-05-26', 'Source Engine Update Available', '<div class=\"post_content\" id=\"content_632\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed command allowing clients to change sv_cheat convars<br/><li>Fixed engine trying to load incorrect skill.cfg file and defaulting game variables<br/></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-05-30', 'Source Engine And Dedicated Server Update', '<div class=\"post_content\" id=\"content_637\" style=\"display: none;\">
<p>An update to the Source Engine and Dedicated server has been released. The update will be applied automatically when your Steam client is restarted. The changes are:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed bug in receive proxies due to a mismatched structure change<br/><li>Fixed crash in SourceTV if AUTO_DISPATCH_MODE was full, had no relays and a new client tried to connect<br/></li></li></ul><br/><b>Media</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Released Episode One launch teaser #3</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-06-22', 'Day Of Defeat Source Summer Update Coming June 28', '<div class=\"post_content\" id=\"content_662\" style=\"display: none;\">
<p><strong>Valve\'s Popular WWII Online Action Game Approaches First Birthday</strong><br/><br/>Bellevue, WA, June 22, 2006 - Valve® announced a Day of Defeat: Source Summer 2006 Update featuring a Free Map Pack is scheduled for release on June 28 via <a href=\"http://www.steampowered.com/\">Steam</a> to everyone who owns a copy of the game. <br/><br/>The Map Pack, which arrives just before DoD: Source\'s 1st birthday, introduces a new gameplay style, Detonation, in two brand new missions (Jagd, Colmar). In addition to the new missions and gameplay style, the Summer 2006 Update also introduces new technical features and gameplay enhancements to Day of Defeat: Source. Some of the new gameplay enhancements - such as spawn clip adjustments, improved hit location detection, and weapon balancing - were made after reviewing the player statistics gathered since the <a href=\"http://www.dayofdefeat.com/stats/\">stats feature</a> was added to DoD: Source earlier this year.</p>
<br clear=\"left\"/>
</div>'),
(300, '2006-06-26', 'New Dod: Source Media', '<div class=\"post_content\" id=\"content_664\" style=\"display: none;\">
<p>The following video highlights the Detonation style gameplay featured in the Jagd map, one of two new maps offered in the free Day of Defeat: Source Summer Update coming this Wednesday.<br/><br/><img src=\"http://www.steampowered.com/img/pointpoint.gif\"/> <a href=\"http://storefront.steampowered.com/v2/index.php?area=game&amp;AppId=917&amp;\">view the DoD Jagd Trailer</a></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-06-27', 'Dod: Source Colmar Trailer Available Now', '<div class=\"post_content\" id=\"content_667\" style=\"display: none;\">
<p>The following video highlights the Detonation style gameplay featured in Colmar, the second of the two new maps offered in the free Day of Defeat: Source Summer Update coming this Wednesday.<br/><br/><img src=\"http://www.steampowered.com/img/pointpoint.gif\"/> <a href=\"http://storefront.steampowered.com/v2/index.php?area=game&amp;AppId=918&amp;\">view the DoD Colmar Trailer</a></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-06-28', NULL, '<div class=\"details\" id=\"June 28, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added new Detonation game mode</li> <li> Added two new Detonation maps: Jagd and Colmar</li> <li> Added film grain and color correction cinematic effects while in spectator</li> <li> Optimizations to the player animation blending system</li> <li> Improved bullet and melee attack hit detection</li> <li> Shortened the BAR reload time</li> <li> Reduced recoil and fire delay on the Garand</li> <li> Added CVAR cl_autorezoom - set to 0 to not rezoom sniper rifles and rocket weapons</li> <li> Added new image-based texture blending shader</li> <li> Added new light warping shader</li> <li> Added new phong Shading/Rim Lighting on player models</li> <li> Added support for bloom on DX8 video cards</li> <li> Added vertex lighting to props</li> <li> Made it more difficult for players to repeatedly block the same cap in order to rack up defend points</li> <li> Added blocking walls to enemy spawn entrances</li> </ul>
Bug fixes
	<ul>
<li> Fixed a case where players could get under terrain in Argentan</li> <li> Fixed player being able to clear mg42 heat by undeploying and redeploying while reloading</li> <li> Fixed stepping over window ledges in Avalanche</li> </ul>
</div>'),
(300, '2006-06-28', 'Day Of Defeat: Source Update Released', '<div class=\"post_content\" id=\"content_668\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added new Detonation game mode<br/><li>Added two new Detonation maps: Jagd and Colmar<br/><li>Added film grain and color correction cinematic effects while in spectator<br/><li>Optimizations to the player animation blending system<br/><li>Improved bullet and melee attack hit detection<br/><li>Shortened the BAR reload time<br/><li>Reduced recoil and fire delay on the Garand<br/><li>Added CVAR cl_autorezoom - set to 0 to not rezoom sniper rifles and rocket weapons<br/><li>Added new image-based texture blending shader<br/><li>Added new light warping shader<br/><li>Added new phong Shading/Rim Lighting on player models<br/><li>Added support for bloom on DX8 video cards<br/><li>Added vertex lighting to props<br/><li>Fixed a case where players could get under terrain in Argentan<br/><li>Made it more difficult for players to repeatedly block the same cap in order to rack up defend points<br/><li>Fixed player being able to clear mg42 heat by undeploying and redeploying while reloading<br/><li>Added blocking walls to enemy spawn entrances<br/><li>Fixed stepping over window ledges in Avalanche</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-08-18', NULL, '<div class=\"details\" id=\"August 18, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Improved hitbox detection for player body parts that extend outside of the bounding box</li> </ul>
Bug fixes
	<ul>
<li> Fixed players being able to capture areas from farther away than intended</li> <li> Fixed an exploit where player could plant the bomb and switch teams, causing the bomb to explode and give the point ownership to the wrong team</li> <li> Fixed bell sound playing on knife impacts</li> <li> Fixed players switching to the tnt view model if they picked it up while a smoke grenade was deployed</li> <li> Fixed several map exploits</li> <li> Fixed minimap cap areas showing the number of players present even if those players were on the owning team</li> <li> Fixed a case where user could crash the server with a client command</li> <li> Fixed a case where dod_Jagd would not respond to mp_timelimit changelevels</li> <li> Fixed an exploit that could be use to throw grenades farther than intended</li> <li> Fixed logging events kill_planter and kill_defuser showing incorrect data</li> <li> Fixed several cvars not being saved in the config ( death effects options, hud_centerid )</li> <li> Fixed animation issue where player would not have an animation if they expended all ammo</li> <li> Fix issue where player would be stuck on spawn if they were defusing when the round restarted</li> </ul>
</div>'),
(300, '2006-08-18', 'Day Of Defeat: Source, Source Engine And Sourcetv Updates Released', '<div class=\"post_content\" id=\"content_724\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source and the Source Engine, along with some improvements to SourceTV have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Improved hitbox detection for player body parts that extend outside of the bounding box<br/><li>Fixed players being able to capture areas from farther away than intended<br/><li>Fixed an exploit where player could plant the bomb and switch teams, causing the bomb to explode and give the point ownership to the wrong team<br/><li>Fixed bell sound playing on knife impacts<br/><li>Fixed players switching to the tnt view model if they picked it up while a smoke grenade was deployed<br/><li>Fixed several map exploits<br/><li>Fixed minimap cap areas showing the number of players present even if those players were on the owning team<br/><li>Fixed a case where user could crash the server with a client command<br/><li>Fixed a case where dod_Jagd would not respond to mp_timelimit changelevels<br/><li>Fixed an exploit that could be used to throw grenades farther than intended<br/><li>Fixed logging events kill_planter and kill_defuser showing incorrect data<br/><li>Fixed several cvars not being saved in the config ( death effects options, hud_centerid )<br/><li>Fixed animation issue where player would not have an animation if they expended all ammo<br/><li>Fixed issue where a player would be stuck on spawn if they were defusing when the round restarted</li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed jittery animations while recording a demo file</li></ul><br/><b>SourceTV</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added a convar \"tv_transmitall\" to transmit all entities (like HLTV)<br/><li>Fixed console messages forwarding for rcon<br/><li>Fixed spectator client crash during round restart<br/><li>Fixed flicking decal and smoke effects<br/><li>Fixed connection retry command<br/><li>Fixed recording and broadcasting player voices. \"tv_relayvoice 0\" turns it off now<br/><li>Fixed missing entities due to wrong PVS culling</li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2006-09-19', 'Source Multiplayer Update Released', '<div class=\"post_content\" id=\"content_753\" style=\"display: none;\">
<p>Updates to the Source Multiplayer Games have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Multiplayer Games</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed console command exploit that could crash multiplayer servers<br/><li>Fixed crash with team swapping in Source Multiplayer Games</li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-01-17', NULL, '<div class=\"details\" id=\"January 17, 2007\" style=\"display: block;\">
Changes/Additions
	<ul>
<li> Replaced cl_interp with cl_interp_ratio. Server can limit it with sv_min_cl_interp_ratio and sv_max_cl_interp_ratio</li> <li> Added sv_rcon_log to allow rcon logging to be disabled</li> <li> Cheat protected a bunch more cvars</li> </ul>
</div>'),
(300, '2007-01-17', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_907\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Replaced cl_interp with cl_interp_ratio. Server can limit it with sv_client_min_interp_ratio and sv_client_max_interp_ratio<br/><li>Added sv_rcon_log to allow rcon logging to be disabled<br/><li>Cheat protected many more cvars</li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-03-12', 'Source Multiplayer Update Released', '<div class=\"post_content\" id=\"content_975\" style=\"display: none;\">
<p>Updates to the Source Multiplayer games have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Multiplayer</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Improved multiplayer voice communication, now using a much clearer codec<br/><li>First release of a completely reworked in game text chat to which now includes a chat history and a filter to only see important chat messages<br/><li>Fixed not being able to use sounds, decals or models if they were downloaded from the server</li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-03-26', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_997\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed crash when running in Offline mode</li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-06-12', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_1074\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted.  The specific changes include:<br/> <br/><b>Pure Servers</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Servers can now force the client to match the server\'s files, by becoming a pure server.  When a server enables sv_pure, clients who connect and play on the server cannot gain an advantage by modifying the game content.  For more information about Pure Servers, <a href=\"http://developer.valvesoftware.com/wiki/Pure_Servers\">click here</a>.</li></ul><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>In-game server browser only shows human players in the player counts column. Bots column now shows number of bots instead of a \"some bots\" or \"no bots\" icon<br/><li>Fixed servers with bots reporting incorrect number of bots when sv_master_legacy_mode is set to 0<br/><li>Fixed a server performance problem with queued packets<br/><li>Increased the maximum rate to 1 megabyte<br/><li>Added a findflags console command, which can list all cvars with a specified flag. For example: \'findflags server_can_execute\' will find all console variables and commands marked with FCVAR_SERVER_CAN_EXECUTE<br/><li>Cheat protected many cvars and commands<br/><li>Removed cl_restrict_server_commands to prevent clients from being redirected<br/><li>Fixed user names reported as \"unconnected\" when greater than 32k players had connected to the server<br/><li>Fixed a client crash during authentication<br/><li>Fixed a crash when mashing the ~ key on disconnect<br/><li>Fixed a bug with sv_minrate and sv_maxrate not applying properly on the client<br/><li>Fixed the free roaming camera in SourceTV demos<br/><li>Fixed cl_language archiving itself and not updating correctly when the language changed<br/><li>Fixed a voice recording bug that could cause voice dropouts<br/><li>Fixed a rare crash when spectating in Counter-Strike: Source</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul> <br/><p>We\'d also like to thank Wim Barelds, TC from UKCS Mega Game Servers and Ray from Clan {US} East, for their time in reporting and testing this update.</p></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-06-14', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_1082\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted.  The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed a client crash<br/><li>Fixed sv_allow_wait_commands restricting the server using wait<br/><li>Fixed a crash in \"soundlist\" command<br/><li>Reallowed fps_max value of 0, which means unrestricted fps<br/><li>Fixed a crash playing back demo files recorded with the previously-released engine<br/><li>Client forwards server commands it doesn\'t understand back to the server<br/><li>sv_pure 1 now allows custom spray decals by default</li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-09-12', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_1191\" style=\"display: none;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted.  The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed custom level sound lists under sv_pure<br/><li>Fixed occasional scrunched-up columns in the serverbrowser<br/><li>Fixed various memory leaks</li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2007-11-12', 'Source Engine Update Released', '<div class=\"post_content\" id=\"content_1308\" style=\"display: ;\">
<p>Updates to the Source Engine have been released. The updates will be applied automatically when your Steam client is restarted.  The specific changes include:<br/><br/><b>Source Engine</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed Half-Life 2: Deathmatch crowbar swing speed difference between Windows and Linux servers<br/><li>Fixed a potential hang bug in the server browser<br/><li>Fixed certain filenames not protected by sv_pure<br/><li>Fixed CSoundEnt spam on the server with high numbers of player slots on a server<br/><li>Fixed Half-Life 2: Deathmatch chat bug on Linux servers<br/><li>Minor optimization to the askconnect panel<br/><li>Fixed IP address column reporting IPs backwards<br/><li>Security fix for file transfers as reported by James Gray<br/><li>Fixed players able to make their name disappear in the scoreboard by setting it to \"~~ ~\" in the options panels</li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2008-05-23', 'Day Of Defeat Steamworks Update In Beta', '<div class=\"post_content\" id=\"content_1594\" style=\"display: none;\">
<p>A new update adding support for Steamworks is currently available in beta for <a href=\"http://storefront.steampowered.com/v/index.php?area=app&amp;AppId=300\">Day of Defeat: Source</a>, the popular World War II online action game from Valve, creators of the Half-Life and Counter-Strike games.<br/>Leveraging the recently released free set of services available in Steamworks, the Day of Defeat update will add 51 achievements for DoD, player avatar display in the scoreboard and win panel, and detailed player statistics integrated with the Steam Community features (<a href=\"http://www.steamcommunity.com\" target=\"_blank\">www.steamcommunity.com</a>).<br/><br/>This update also adds support for popular features introduced in Valve\'s <a href=\"http://storefront.steampowered.com/v/index.php?area=app&amp;AppId=440\">Team Fortress 2</a> (TF2), the PC title named multiplayer game of the year by Gamespy.com and PC Gamer. These include \"nemesis/revenge\" freeze cam and new effects driven by the particle system introduced to the Source engine for TF2.<br/><br/>In addition, this update will also introduce a new map, dod_Palermo, which is a remix of the most popular community map, dod_salerno.<br/><br/>Owners of Day of Defeat: Source, retail and Steam versions, may join the beta free of charge.</p>
<br clear=\"left\"/>
</div>'),
(300, '2008-05-27', 'Day Of Defeat: Source Beta Update Released', '<div class=\"post_content\" id=\"content_1597\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source Beta have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source Beta</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed possible crash when a rocket explodes<br/></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2008-05-28', 'Day Of Defeat: Source Beta Update Released', '<div class=\"post_content\" id=\"content_1600\" style=\"display: none;\">
<p>Updates to Day of Defeat: Source Beta have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source Beta</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fix for client crash in spectator gui<br/><li>Fixed third person tracers not drawing properly<br/><li>Reverting view position change when sniper zoomed<br/><li>Added cvars dod_playrivalrysounds and dod_playachievementsound<br/><li>Suicide no longer removes a kill<br/><li>Fixed bullet decals being misaligned when iron sighted<br/><li>Fixed being able to dominate a teammate if friendlyfire was on<br/><li>sv_friction and sv_stopspeed are now accessible again<br/><li>Reduced size of impact effects at distance<br/><li>Fix for deployed bazooka and mg having full mouse sensitivity<br/><li>Fix for iron sight deploy animation sometimes taking longer<br/><li>Player avoidance now prevents stationary players from occupying the same space<br/><li>Some particle systems updated<br/><li>Fixes to the custom map achievement<br/></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(300, '2008-06-03', 'Day Of Defeat: Source Beta Update Released', '<div class=\"post_content\" id=\"content_1602\" style=\"display: ;\">
<p>Updates to Day of Defeat: Source Beta have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Day of Defeat: Source Beta</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added Steamworks stats<br/><li>New team identifier icons as rewards for completing achievements - 1 per class achievement, and 1 for completing all achievements<br/><li>Added cvar dod_friendlyfiresafezone - units around the player where they will do no direct damage on FF on servers ( default 100 units )<br/><li>Dropping a weapon in the spawn and changing class will now fizzle out the dropped weapon<br/><li>Fixed unducking while jumping potentially getting you stuck in the roof<br/><li>Player model fixes to address the \'left peek\' issue<br/><li>Fixed kb_act default binding for large map being broken<br/><li>Marked r_screenfademinsize and r_screenfademaxsize as cheats<br/><li>Players now respawn even if they have the class menu up - changing class will respawn them instantly now<br/><li>Fixed \"Don\'t Tread On Me\" achievement triggering off of bomb defuses<br/><li>Fixed long range rocket achievement being awarded when you kill an ironsight k98 or garand<br/><li>Fixed picking up an mg42 with an empty clip playing the wrong animation<br/><li>Achievement progress now stored in steam<br/><li>Added more default crosshairs<br/><li>Adjusted scoreboard to make the local player a bit more readable<br/></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>');
