-- Steam Platform Update History
-- App ID: 2400
-- Generated on: 2025-08-01 23:46:09
-- MySQL/MariaDB Format



INSERT INTO `platform_update_history` (`appid`, `date`, `title`, `content`) VALUES
(2400, '2006-07-11', NULL, '<div class=\"details\" id=\"July 11, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Initial release of The Ship</li> </ul>
</div>'),
(2400, '2006-07-11', 'The Ship Available Now Via Steam', '<div class=\"post_content\" id=\"content_685\" style=\"display: none;\">
<p>The Ship, a massively mysterious thriller (MMT) from Outerlight Ltd, is available now via Steam, Valve\'s electronic distribution platform. Set onboard a 1920\'s luxury liner, Mr X, the Ship\'s owner has \"invited\" you to a mysterious multiplayer game of hunt and hunted, as players must secretly track and extinguish specified passengers while avoiding similar fate. The ship is available for just $19.95. <a href=\"http://storefront.steampowered.com/v2/index.php?area=game&amp;AppId=2400\">Click here</a> for more details.</p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-07-12', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_688\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Dedicated servers will now be able to see the SteamId of players</li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-07-17', NULL, '<div class=\"details\" id=\"July 17, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Weapon fines and sentences balanced</li> <li> Default witness count set to 2</li> <li> Default witness time set to 1 second</li> <li> Scoreboard is no longer showable whilst in court, and no longer gets stuck up when leaving court</li> <li> Hunters who have already killed their quarry no longer get a \"Quarry Reassigned\" message when their old quarry leaves the game</li> <li> Pee sounds tweaked</li> <li> Increased the cost of bribing guards to ignore security breaches</li> <li> Increased the cost of healing at sickbay</li> <li> Balanced ambient soundscapes in various maps</li> <li> Players can now click-through the court screen to start serving their sentence immediately</li> <li> Players can now chat with others while in court</li> <li> Players who now set others on fire when they are burning get accredited for the kill correctly</li> </ul>
Bug fixes
	<ul>
<li> Fixed a number of server stability issues</li> <li> Fixed breaking-down doors</li> <li> Fixed occasional map-wide jumping problem (jump going in random direction)</li> <li> Fixed context sensitive interface (CSI) positioning issues in all aspect ratios</li> <li> Fixed containers getting stuck open when the player using them is killed</li> <li> Fixed container/shop/CSI panels that were left shown to a player when that player dies</li> <li> Fixed attachments not being removed from the player model when they are dropped from the inventory</li> <li> Fixed water dripping from hands on other players</li> <li> Correct water effect for different sized sinks</li> <li> Correct sounds added to the metal pressure doors</li> </ul>
</div>'),
(2400, '2006-07-17', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_690\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted.</p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-07-20', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_696\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>A number of server stability fixes<br/><li>Fixed weapon ammo amount when dropped from inventory<br/><li>Money for kills values for weapons are now halved (by default) as soon as a weapon is used (and each time thereafter) within a round, and then reset to the minimum value at the end of a round<br/><li>Fixed visual effects being played when they shouldn\'t (e.g. dripping hands)<br/><li>Fixed flames being left behind when player arrested<br/><li>\'/\' characters now work within chat</li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-08-01', NULL, '<div class=\"details\" id=\"August 1, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added Linux Dedicated Server (Beta)</li> <li> Tightened Kick/Ban system defaults</li> <li> Added console chat for admins</li> <li> Lighting on characters improved</li> <li> Increased warm-up time before game begins on a server from 30 to 60 seconds</li> <li> Axe containers now appear empty when no axe is in them</li> </ul>
Bug fixes
	<ul>
<li> Fixed a number of client and server stability issues</li> <li> Fixed ERRORNAME bug</li> <li> Fix for suicide exploit - suicide via the \'kill\' command has a 60 second delay</li> <li> Fixed another version of the dripping hands bug</li> <li> Fixed incorrect MFK displayed in inventory, shops and containers for purse bomb</li> <li> Added missing fallback water textures for older video cards</li> <li> Fixed hands disappearing from a few player models</li> <li> Fixed bug to maintain bot presence on a server</li> <li> Fixed bug where you were given different hat/glasses/hair when not killed by your Hunter</li> </ul>
</div>'),
(2400, '2006-08-01', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_712\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed a number of client and server stability issues<br/><li>Added Linux Dedicated Server (Beta)<br/><li>Fixed ERRORNAME bug<br/><li>Tightened Kick/Ban system defaults<br/><li>Added console chat for admins<br/><li>Fix for suicide exploit - suicide via the \'kill\' command has a 60 second delay<br/><li>Fixed another version of the dripping hands bug<br/><li>Fixed incorrect MFK displayed in inventory, shops and containers for purse bomb<br/><li>Added missing fallback water textures for older video cards<br/><li>Fixed hands disappearing from a few player models<br/><li>Lighting on characters improved<br/><li>Fixed bug to maintain bot presence on a server<br/><li>Fixed bug where you were given different hat/glasses/hair when not killed by your Hunter<br/><li>Increased warm-up time before game begins on a server from 30 to 60 seconds<br/><li>Axe containers now appear empty when no axe is in them</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-08-02', NULL, '<div class=\"details\" id=\"August 2, 2006\" style=\"display: none;\">
Bug fixes
	<ul>
<li> Fixed crash when changing key bindings</li> </ul>
</div>'),
(2400, '2006-08-02', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_713\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed crash when changing key bindings</li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-09-13', NULL, '<div class=\"details\" id=\"September 13, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> New multiplayer map - Connemara</li> <li> New multiplayer map - Cotopaxi</li> <li> Existing multiplayer maps updated with various bug fixes</li> <li> New Tutorial added (to allow new players to learn various aspects of the game)</li> <li> Added new voice overs for various crew</li> <li> Added new voice overs for player reactions</li> <li> Identity and Quarry portraits on HUD now look in the correct direction</li> <li> Improved performance of Bots</li> <li> Changed end of round sequence so the round always finishes before changing to the next map</li> <li> Added a small delay when scrolling through weapons to make sure only one is changed at a time</li> <li> Improved peformance for security</li> <li> In-game music volume can now be adjusted from audio options</li> <li> Added sounds for players peeing and pooing themselves</li> <li> Added an animation for the Psychiatrist once the player is finished being healed and when being healed</li> <li> Added sound for elevator arriving at a floor</li> <li> Changed witnessing another player in wrong-sex room to play a squeal sound for players witnessing them instead of playing an alarm sound</li> <li> When players talk to crew they now continue to talk to the player until the player is finished talking</li> <li> Changed voice sounds for Steward crew members</li> <li> Added eat candy animation</li> <li> Stopped creating a wallet or purse for players who are dead and disconnect</li> <li> Added sounds when a player is arrested, charged for trespassing and charged in court room</li> <li> Added shank weapon</li> <li> Removed decals on characters</li> <li> Added new male suit outfit</li> <li> Improved quality of all user interface textures when running game using medium or low detail textures</li> <li> Improved deckplans for all maps</li> <li> Incresed overall volume of footstep sounds</li> <li> Improved Shopkeeper, Nurse and Barman voice-over sounds</li> <li> Improved pee and poo sounds</li> <li> Added Russian localization of text</li> <li> Improved layout of item information in Inventory, shops and containers to allow for longer localised text</li> </ul>
Bug fixes
	<ul>
<li> Crash fixed when player in trap leaves the game</li> <li> Script names changed to load correctly with Linux dedicated server</li> <li> Fixed \'infinite satchels\' exploit</li> <li> Fixed bug with Quarry location not updating after being healed or in jail</li> <li> Fixed floating characters bug</li> <li> Fixed bug when interacting with things whilst jumping</li> <li> Fixed incorrect examine descriptions</li> <li> Fixed secondary messages so words are not split for long messages</li> <li> Fixed possible Steam connection issues</li> <li> Added 2 new columns to in-game server browser to show the game mode and witnesses settings for each server</li> <li> Fixed sound for characters on-fire</li> <li> Fixed bug where you could be stuck standing in a bed when hit while sleeping</li> <li> Fixed bug with Bots sometimes flying off after interacting with something</li> <li> Fixed changing clothes animation bug when in Inventory</li> <li> Fixed bug with hunger needs satisfiers</li> <li> Fixed localization text for all languages</li> </ul>
</div>'),
(2400, '2006-09-13', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_748\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted.</p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-09-28', NULL, '<div class=\"details\" id=\"September 28, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Improved Bot interactions and navigation</li> <li> Improved players getting out of interactions when other players are close by</li> <li> Improved player spawn to minimise the situation where players spawn in the same cabin as other players</li> <li> Added \"Inventory Full\" message for a player trying to holster when their Inventory is full</li> <li> Fixed bug with Security Guard field of view</li> <li> New read plaque animation</li> <li> Added new props for players eating crisps and sandwiches</li> <li> Added more shank weapon spawners</li> <li> Improved Bot navigation in Atalanta and Cyclops</li> <li> Added life boat dropping sound</li> <li> Improved elevator sounds</li> <li> Improved sprinting under high lag situations</li> </ul>
Bug fixes
	<ul>
<li> Fixed fall damage so that players die when falling from great heights</li> <li> Fixed bug with players not being able to read in Prison</li> <li> Fixed bug with players not being able to equip or holster items in Prison</li> <li> Fixed lift collision crash bug on Huronian</li> <li> Fixed repeating decals</li> <li> Fixed wrong decals on doors</li> <li> Fixed positioning for knife and fork attachments when players eat</li> <li> Fixed glass attachment when players drink</li> <li> Fixed smokestack on all multiplayer maps</li> <li> Various map fixes for all multiplayer maps</li> <li> On-going deckplan fixes for all multiplayer maps</li> <li> Fixed paddle trap on Atlanta so that the hunter gets awarded correctly for killing their Quarry</li> </ul>
</div>'),
(2400, '2006-09-28', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_766\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed fall damage so that players die when falling from great heights<br/><li>Fixed bug with players not being able to read in Prison<br/><li>Fixed bug with players not being able to equip or holster items in Prison<br/><li>Improved Bot interactions and navigation<br/><li>Fixed lift collision crash bug on Huronian<br/><li>Improved players getting out of interactions when other players are close by<br/><li>Improved player spawn to minimise the situation where players spawn in the same cabin as other players<br/><li>Added \"Inventory Full\" message for a player trying to holster when their Inventory is full<br/><li>Fixed bug with Security Guard field of view<br/><li>New read plaque animation<br/><li>Fixed repeating decals<br/><li>Fixed wrong decals on doors<br/><li>Fixed positioning for knife and fork attachments when players eat<br/><li>Fixed glass attachment when players drink<br/><li>Added new props for players eating crisps and sandwiches<br/><li>Added more shank weapon spawners<br/><li>Fixed smokestack on all multiplayer maps<br/><li>Improved Bot navigation in Atalanta and Cyclops<br/><li>Various map fixes for all multiplayer maps<br/><li>On-going deckplan fixes for all multiplayer maps<br/><li>Added life boat dropping sound<br/><li>Improved elevator sounds<br/><li>Fixed paddle trap on Atlanta so that the hunter gets awarded correctly for killing their Quarry<br/><li>Improved sprinting under high lag situations</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-11-16', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_835\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>New Features</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added system to allow players to opt in and out of a game using a button on the scoreboard<br/><li>Added join as passenger or killer option on joining<br/><li>When players sit down they now stay sitting for a while and can look around until they cancel sitting or they have been sitting for a long time<br/><li>Added new player models, outfits and hats</li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-11-24', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_847\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>New Features</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added cash and truncheon body groups for the security guards<br/><li>Fixed Single-Player fence mission special items not respawning after failing mission<br/><li>Fixed Single-Player fence sometimes not reapearing when the mission is failed<br/><li>Fixed Syringe being on MFK table multiple times<br/><li>Fixed using consumable item after holstering a weapon then unholstering resulting in wrong weapon<br/><li>Fixed player view height when sitting after ducking<br/><li>Fixed footstep sounds sometimes not playing after spawning<br/><li>Weapon switching disabled when scoreboard is up<br/><li>Looked doors should all now have the locked examine description<br/><li>Corpse Container crosshair changes to examine icon when someone else is using it<br/><li>Corpse container sound changed<br/><li>Problem with number of players in game fixed for listen servers after listen server disconnects and restarts<br/><li>Weapons no longer get drawn floating in mid-air at the origin of the map before players have been in the same part of the map as each other<br/><li>Fixed picking up lots of items in jail resulting in legal items the player was carrying before not being returned<br/><li>Console message to say when the \'kill\' request will be granted now appears in client console instead of server console<br/><li>Players are now healed between rounds if they are poisoned or on fire<br/><li>Bunny-hopping exploit not allowed now<br/><li>Fixed bug with weapon being available after innocent kill but not being drawn<br/><li>Flare now registers a valid kill<br/><li>French keyboard layout used when Steam language is French<br/><li>Surface properties for models fixed - large and small Capstand, cleaner\'s A-stand, trolly dolly, all bins and hand dryer<br/><li>V Model for shank improved<br/><li>Balanced item spawners for all maps<br/><li>Fixed container busy message appearing sometimes when you are already using a container<br/><li>Added ballgown and kilt shop mannequins and stopped these costumes spawning in other containers<br/><li>Fixed Polish language support</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-12-13', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_876\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added a new version of the Batavier map with Christmas decor and music<br/><li>Added Santa Hats<br/><li>Changed front end screens to Christmas versions for the Christmas period<br/><li>Added HDR lighting for Atlanta map<br/><li>Added some secret areas<br/><li>Fixed knife blocks in all maps<br/><li>Fixed Huronian beach ball surface property<br/><li>Fixed wrongly parented door interaction in Rubicon bank<br/><li>Added nodraw func_detail collision to containers to allow ragdoll collision<br/><li>Fixed text on court slip for sleeping potion syringe<br/><li>Fixed camera height when sitting from a crouch in single player mode<br/><li>Fixed empty syringes being put in containers appearing as full<br/><li>Fixed round summary text to be centered on screen<br/><li>Golf bag, knife block, pool cue, flare gun cabinet and gun cabinet containers change when items are taken from them and when items are spawned in them to show how many items are in them<br/><li>Tommygun muzzle flash effects now linked to VFX detail level<br/><li>Fixed font corruption in Polish, Russian and Japanese</li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-12-13', NULL, '<div class=\"details\" id=\"December 13, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> MERRY CHRISTMAS! - Added a new version of the Batavier map with Christmas decor and music</li> <li> Added Santa Hats</li> <li> Changed front end screens to Christmas versions for the Christmas period</li> <li> Added HDR lighting for Atalanta map</li> <li> Added some secret areas</li> <li> Added nodraw func_detail collision to containers to allow ragdoll collision</li> <li> Golf bag, knife block, pool cue, flare gun cabinet and gun cabinet containers change when items are taken from them and when items are spawned in them to show how many items are in them</li> <li> Tommygun muzzle flash effects now linked to VFX detail level</li> </ul>
Bug fixes
	<ul>
<li> Fixed knife blocks in all maps</li> <li> Fixed Huronian beach ball surface property</li> <li> Fixed wrongly parented door interaction in Rubicon bank</li> <li> Fixed text on court slip for sleeping potion syringe</li> <li> Fixed camera height when sitting from a crouch in single player mode</li> <li> Fixed empty syringes being put in containers appearing as full</li> <li> Fixed round summary text to be centered on screen</li> <li> Fixed font corruption in Polish, Russian and Japanese</li> </ul>
</div>'),
(2400, '2006-12-20', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_883\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added voting system for changing map (\"/votemap\"), changing mode (\"/votemode\") and kicking players (\"/votekick\"), all of which can be activated via chat<br/><li>Added key bindings for voting \"yes\" (default F1) or \"no\" (default F2) when someone starts a vote<br/><li>Added convars to allow server admins to disable any of the 3 voting systems<br/><li>Added new ambient music to all maps<br/><li>Added a new dance animation for females and males<br/><li>Fixed bug with weapon animations sometimes not playing for other players after first hit<br/><li>Keyboard settings in game are now based on your PC\'s keyboard settings not the language set in Steam<br/><li>Various fixes in Cyclops map<br/><li>Fixed collision for bank counter in Connemara map<br/><li>Fixed exploit when released from prison with un-holstered weapon</li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2006-12-20', NULL, '<div class=\"details\" id=\"December 20, 2006\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added voting system for changing map (\"/votemap\"), changing mode (\"/votemode\") and kicking players (\"/votekick\"), all of which can be activated via chat</li> <li> Added key bindings for voting \"yes\" (default F1) or \"no\" (default F2) when someone starts a vote</li> <li> Added convars to allow server admins to disable any of the 3 voting systems</li> <li> Added new ambient music to all maps</li> <li> Added a new dance animation for females and males</li> <li> Fixed bug with weapon animations sometimes not playing for other players after first hit</li> <li> Keyboard settings in game are now based on your PC\'s keyboard settings not the language set in Steam</li> <li> Various fixes in Cyclops map</li> <li> Fixed collision for bank counter in Connemara map</li> <li> Fixed exploit when released from prison with un-holstered weapon</li> </ul>
</div>'),
(2400, '2007-01-09', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_899\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Added a new column called \"Humans\" to server browser. It will display number of non-bot players on a server<br/><li>Changed background screens to normal (non-Christmas) versions<br/><li>Stopped players being able to spawn in wearing a Santa hat<br/><li>Polish and Russian localisation fixes</li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2007-01-09', NULL, '<div class=\"details\" id=\"January 9, 2007\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added a new column called \"Humans\" to server browser. It will display number of non-bot players on a server</li> <li> Changed background screens to normal (non-Christmas) versions</li> <li> Stopped players being able to spawn in wearing a Santa hat</li> </ul>
Bug fixes
	<ul>
<li> Polish and Russian localisation fixes</li> </ul>
</div>'),
(2400, '2007-02-01', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_938\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>New map added - Raifucu Maru<br/><li>New outfits added - Safari outfit and Farmer outfit<br/><li>New Team Modes - Team VIP and Team Elimination<br/><li>Added Russian Voice Over for Single-Player<br/><li>Throwing a wallet or purse bomb at a door now results in it being slid along the floor so you can slide one under doors to blow up door-blocking players<br/><li>Added 20 seconds delay after unsuccessful vote to stop players trying to vote too often<br/><li>Added option for server admins to set a server to randomly choose the game mode<br/><li>Added option for server admins to reset the game mode back to default setting after a map change<br/><li>Added sound when players don\'t have sufficient funds to buy from a shop<br/><li>Added music for Ambassador\'s cabin in Single-Player map and Cotopaxi map<br/><li>Added new music to Andrea Doria, Cyclops and Huronian</li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2007-02-01', NULL, '<div class=\"details\" id=\"February 1, 2007\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> New map added - Raifucu Maru</li> <li> New outfits added - Safari outfit and Farmer outfit</li> <li> New Team Modes - Team VIP and Team Elimination</li> <li> Added Russian Voice Over for Single-Player</li> <li> Throwing a wallet or purse bomb at a door now results in it being slid along the floor so you can slide one under doors to blow up door-blocking players</li> <li> Added 20 seconds delay after unsuccessful vote to stop players trying to vote too often</li> <li> Added option for server admins to set a server to randomly choose the game mode</li> <li> Added option for server admins to reset the game mode back to default setting after a map change</li> <li> Added sound when players don\'t have sufficient funds to buy from a shop</li> <li> Added music for Ambassador\'s cabin in Single-Player map and Cotopaxi map</li> <li> Added new music to Andrea Doria, Cyclops and Huronian</li> </ul>
Bug fixes
	<ul>
<li> AI will now only play shocked animations when a player is killed in view</li> <li> You can now run The Ship Dedicated Server via the Steam UI with a Steam account that does not have The Ship registered with it</li> <li> Improved Lag compensation to improve attacking with weapons in higher lag situations</li> <li> Russian and Polish localisation fixes</li> <li> Fixed bedpan interaction so players use them properly</li> <li> Transparency issue with Syringes fixed</li> <li> Fixed Steam trap in Engineering in Rubicon map</li> <li> Various lighting fixes and optimisations in Rubicon map</li> <li> Changed Cotopaxi cafe music</li> <li> Various sound levels tweaked</li> <li> Increased volume for English Tutorial voice over</li> <li> Players now play reading animation when reading magazines</li> <li> Fixed wrong hats and glasses sometimes appearing on players</li> <li> Fixed bug with jumping animation sometime not playing for other players</li> <li> Fixed player spawning so players don\'t spawn in same cabin if there\'s an empty cabin available</li> <li> Fixed bug with players being able to escape from jail after sleeping</li> <li> Players who poison or set fire to their Quarry will now get awarded for the kill even if their Quarry disconnects</li> <li> Fixed bug with Doctor or Psychiatrist sometimes standing up instead of sitting</li> <li> Added missing doors on Connemara Deckplan</li> <li> Added missing door on Atalanta Deckplan</li> <li> Added missing Mall Cafe on Connemara Deckplan</li> <li> Added missing Swimming Pool and Hottub on Rubicon Deckplan</li> </ul>
</div>'),
(2400, '2007-02-02', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_941\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed crash bug when players disconnect from Raifucu Maru while in water<br/><li>Fixed client crash when team scoreboard visible during map change<br/><li>Added missing file msvcr71.dll</li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2007-02-02', NULL, '<div class=\"details\" id=\"February 2, 2007\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Added missing file msvcr71.dll</li> </ul>
Bug fixes
	<ul>
<li> Fixed crash bug when players disconnect from Raifucu Maru while in water</li> <li> Fixed client crash when team scoreboard visible during map change</li> </ul>
</div>'),
(2400, '2007-02-08', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_945\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Replaced \"/votekick\" in chat with a new system. Now you can vote to kick players by right-clicking on them from the scoreboard<br/><li>Fixed rcon / Dedicated Server chat crash<br/><li>Added commands to switch to player, team and identity chat, default key binding have been added for them<br/><li>Fixed some UI panels disappearing after switching resolution and screen mode<br/><li>Killing inactive players in VIP mode no longer strips them of their weapons, and killing active players now results in their weapons being left in their corpse instead of cleared</li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2007-02-08', NULL, '<div class=\"details\" id=\"February 8, 2007\" style=\"display: none;\">
Changes/Additions
	<ul>
<li> Replaced \"/votekick\" in chat with a new system. Now you can vote to kick players by right-clicking on them from the scoreboard</li> <li> Added commands to switch to player, team and identity chat, default key binding have been added for them</li> <li> Killing inactive players in VIP mode no longer strips them of their weapons, and killing active players now results in their weapons being left in their corpse instead of cleared</li> <li> Friendly fire is now off by default for Team Modes</li> <li> Moved team round respawn to the end of the start of round countdown, so that countdown completes, then teams respawn</li> <li> Team respawn at end of countdown fixes putting the player in amongst the enemy when changing teams between rounds</li> <li> Removed dependency for msvcr71.dll</li> <li> Fixed kitchen name and cash icons on Raifucu Maru deckplan</li> <li> VIP now spawns as far away from friendlies as he can when he dies of needs/suicide, which makes him a sitting duck for his hunters, who get an immediate update on his new location</li> </ul>
Bug fixes
	<ul>
<li> Fixed rcon / Dedicated Server chat crash</li> <li> Fixed some UI panels disappearing after switching resolution and screen mode</li> <li> Fixed items spawning too quickly when items are removed from containers</li> <li> Passengers now do not wear outfits reserved for Teams in Team Modes</li> <li> Passengers or players in jail no longer get frozen or respawned at the start of a new round</li> <li> Sprinting without a movement button pressed no longer effects your sprint capacity or fatigue</li> <li> Flare\'s now correctly collide with doors</li> <li> Fixed wallets sticking around after going overboard</li> </ul>
</div>'),
(2400, '2007-02-26', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_960\" style=\"display: none;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed problem with Server Browser when running with a language that is not supported<br/><li>Added some support for new languages (Danish, Dutch, Finnish, Norwegian and Swedish), The Ship specific text will still be in English for these languages though<br/><li>Fixed bug with some chat messages not appearing correctly for Russian and Polish languages<br/><li>Localization fixes for French, German, Italian, Polish, Russian and Spanish languages<br/><li>Fixed possible crash bug when players try to pick up a wallet and purse at the same time<br/><li>Improved stability for Linux Dedicated Servers</li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2007-02-26', NULL, '<div class=\"details\" id=\"February 26, 2007\" style=\"display: block;\">
Changes/Additions
	<ul>
<li> Added some support for new languages (Danish, Dutch, Finnish, Norwegian and Swedish), The Ship specific text will still be in English for these languages though</li> <li> Improved stability for Linux Dedicated Servers</li> </ul>
Bug fixes
	<ul>
<li> Fixed problem with Server Browser when running with a language that is not supported</li> <li> Fixed bug with some chat messages not appearing correctly for Russian and Polish languages</li> <li> Localization fixes for French, German, Italian, Polish, Russian and Spanish languages</li> <li> Fixed possible crash bug when players try to pick up a wallet and purse at the same time</li> </ul>
</div>'),
(2400, '2007-03-29', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_1003\" style=\"display: ;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed players getting stuck when they are too close to NPCs when they respawn<br/><li>Piranhas no longer produce blood effect before actually arriving<br/><li>Fixed bug with players leaving while in court not being put in jail when rejoining game<br/><li>Fixed color of Eye-Of-Doom on HUD after switching to full-screen or switching resolution<br/><li>Fixed color of mission text in Single-Player game after switching to full-screen or switching resolution<br/><li>Fixed mission text changing language in Single-Player game after switching to full-screen or switching resolution<br/><li>Stopped players being arrested while in a trespass zone when a game finishes<br/><li>Stopped suicide message appearing twice on HUD</li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(2400, '2008-03-10', 'The Ship Update Released', '<div class=\"post_content\" id=\"content_1478\" style=\"display: ;\">
<p>Updates to The Ship have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>The Ship</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed bug where you could noclip when jumping at the same time as interacting with something<br/><li>Improved weapon combat under higher lag situations<br/><li>Sounds and decals now get loaded correctly from custom maps that have these files zipped into the BSP<br/><li>Fixed potential crash with very long chat messages<br/><li>Fixed bug where fatigue was not going up while sprinting if you sprinted when you woke up<br/><li>Fixed bug with players not being able to get other player names<br/><li>Fixed bug where Quarry location was still being shown on map even though player has no Quarry<br/><li>Bots no longer consider prison areas when looking for interactions outside of prison<br/><li>Bots no longer think they are trespassing when in a toilet room meant for them (i.e. male toilet for male Bots)<br/><li>Don\'t arrest a player if they have been killed just after the arrest process has begun<br/><li>Single Player - Needs are now reset when you fail a mission<br/></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>');
