-- Steam Platform Update History
-- App ID: 15620
-- Generated on: 2025-08-02 00:05:19
-- MySQL/MariaDB Format



INSERT INTO `platform_update_history` (`appid`, `date`, `title`, `content`) VALUES
(15620, '2009-02-18', 'Warhammer 40,000: Dawn of War II Now Available', '<div class=\"post_content\" id=\"content_2261\" style=\"display: none;\">
<p><a href=\"http://store.steampowered.com/app/15620/\">Warhammer® 40,000™: Dawn of War® II</a> is now available on Steam for customers in most parts of the world. European customers will be able to play, starting Friday morning (GMT).<br/><br/>Developed by award winning Relic Entertainment, Dawn of War II ushers in a new chapter in the acclaimed RTS series - taking players to the brutal frontlines of war to lead an Elite Strike Force on a mission to save the galaxy.</p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-02-20', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2276\" style=\"display: none;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Warhammer 40,000: Dawn of War II</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed a bug that caused missions to stop populating. Regular save games should not be affected while previous \'stalled\' save games should now continue normally<br/></li></ul></p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-02-23', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2285\" style=\"display: none;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Warhammer 40,000: Dawn of War II</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Improved memory heap management to reduce \'out-of-memory\' crashes that were plaguing certain systems, including 32-Bit Vista on High and Ultra settings. Often reported as \'error 183 failed to create to create dump\'<br/></li></ul></p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-03-02', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2305\" style=\"display: none;\">
<p>A change is being made on Games for Windows ® LIVE today to improve the Multiplayer experience for Warhammer 40,000: Dawn of War II players. Ranked and Custom game modes requiring Games for Windows ® LIVE will now only match players using the latest version of the game. Players should see a higher percentage of compatible games in the custom games list and reduced search times during matchmaking. Players with an out of date version of Warhammer 40,000: Dawn of War II will need to connect to Steam in \'online mode\' to download the latest patch.<br/><br/>Players choosing to remain in \'off-line\' mode will continue to have access to off-line Campaign and LAN game modes without connecting to Games for Window ® LIVE or Steam.</p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-03-10', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2331\" style=\"display: ;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Warhammer 40,000: Dawn of War II</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Addressed a Population Cap issue where during reinforcement, the final unit reinforced charged twice the population cap to the player.  *NOTE* â€“ This is part of 1 of a 2 part fix. There are still a few edge cases where the bug could occur. They are however, rare and require intended exploitation in order to recreate.  Our next patch will completely resolve this issue but requires further testing and certification<br/><li>Fixed an issue where users with the top end video cards were unable to select Ultra settingg<br/><li>Fixed a Fatal Scar error in Mission D (Angel Forge)<br/></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-04-13', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2405\" style=\"display: ;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Warhammer 40,000: Dawn of War II</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>New Team Battle map added! \"(6p) Tiber Outpost\" is now available for play in Custom Matches<br/><li>Tyranid Warrior Adrenal Gland upgrade damage reduced from 52 to 40<br/><li>Energy Shields no longer regenerate while active â€“ This includes the Zoanthrope, Falcon, Hive Tyrant, Warlock, Force Commander, Mekboy and Techmarine<br/><li>Energy Shield conversion modifier reduced from .2 to .25<br/><li>Energy Shields now have an 8 second toggle on / toggle off time<br/><li>Falcon Energy regeneration reduced from 3 to .5<br/><li>Melee damage reduction versus Rippers reduced from .25 to .3<br/><li>Zoanthrope Focus Blast now immobilizes vehicles for 12 seconds from 15<br/><li>Guardian Battle Equipment cost increased to 50/15 from 40/10<br/><li>Carnifex cost increased to 600/135 from 550/125<br/><li>Tactical Sergeant\'s melee special attack reduced to 28 from 50<br/><li>\"And They Shall Know No Fear\" now debuffs Tactical Marine melee damage by .6<br/><li>Spore Mines can no longer enter Ravener Tunnels and Webway Gates<br/><li>Warp Spider deathspinner damage increased from 20 to 30<br/><li>Warp Spider Exarch dual deathspinner damage increased from 30 to 35<br/><li>Implemented final fixes for the Population Cap issue as noted in Patch 1.1.3. This included reverting the temporary changes made in Patch 1.1.3<br/><li>Fixed an issue where campaign completion achievements were sometimes not awarded<br/><li>Fixed an issue where players were awarded a win in Ranked multiplayer matches after modifying local files<br/><li>Fixed an issue with automatching code to help provide better quality matches based on TrueSkill Rankings<br/><li>Fixed an issue allowing players with mismatched data to be grouped together<br/><li>Updated BugSplat error reporting to new version<br/></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-05-12', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2495\" style=\"display: none;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>New Content</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Two on Two game mode is now available for ranked play.<br/><li>Two new four-player maps have been added to the game: (4p) Medean Cliff Mines and (4p) Ruins of Argus. These are available for ranked and custom games.<br/><li>We have added a benchmarking performance test; you can find it in the Graphics options tab.<br/><li>There are eight new sync kill animations in the game. Keep your eyes open for some new carnage!<br/></li></li></li></li></ul><br/><b>New Options</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>We have added a \"Push to Talk\" option for in-game voice chat. When enabled in the Game Options screen, tilde (~) will control chat.<br/><li>We have also added a \"Advanced Sub-selection\" game option. When enabled sub-selection behavior will be the same as Company of Heroes, where a sub-selected squad will be the only one to receive orders. <br/></li></li></ul><br/><b>Stability</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Fixed several crashes where invalid data was being written to logs.<br/><li>Fixed a common multithreading crash.<br/><li>Fixed some out-of-memory crashes on Vista 32.<br/><li>Fixed a crash that could occur if Avitus was reinforcing when a game ended. <br/></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>'),
(15620, '2009-05-19', 'Warhammer 40,000: Dawn of War II Update Released', '<div class=\"post_content\" id=\"content_2521\" style=\"display: ;\">
<p>Updates to Warhammer 40,000: Dawn of War II have been released. The updates will be applied automatically when your Steam client is restarted. The specific changes include:<br/><br/><b>Warhammer 40,000: Dawn of War II</b><br/><ul style=\"padding-bottom: 0px; margin-bottom: 0px;\"><li>Adjusted the Orbital Bombardment ability to increase damage. Outer radius increased to 150 from 100<br/><li>Fixed an issue in the campaign where one point was getting auto-allocated at level-up if the player resumed an old campaign<br/><li>Made changes to the Mekboy mines. The mines now do drastically less damage and suppress infantry<br/><li>Adjusted lighting on 6P Tiber Outpost<br/><li>Fixed an issue where Guardian squads would switch to melee stance if upgraded with a Warlock, then with Battle Equipment<br/><li>Regenerated AI tuning data<br/></li></li></li></li></li></li></ul></p>
<br clear=\"left\"/>
</div>');
